routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', '/login');

Route::get('reset_password/{token}', ['as' => 'password.reset', function($token)
{
    // implement your reset password route here!
}]);

// Route::get('/', function () {
//     return view('welcome');
// });

// Auth::routes();
Auth::routes([
	'verify' => true,
	'register' => false
]);

Route::middleware(['auth', 'verified'])->group(function(){
	Route::get('/home', 'HomeController@index')->name('home');
	// Route::any('navdetails');

	Route::resource('organization', 'OrganizationController');

	/*
	 * Setup Routes
	 */
	Route::any('createsetup/{type}', 'SetupsController@createsetup');
	Route::get('setups', 'SetupsController@index');
	Route::any('updatesetup/{setup}/{type}', 'SetupsController@updatesetup');
	Route::post('updatesmstemplateguide', 'SetupsController@updatesmstemplateguide');

	// Route::get('/registercallback/{shortcode}', 'PaybillController@registercallback');
	// Route::get('/testtransaction/{shortcode}', 'PaybillController@testtransaction');
	// Route::post('submittesttransaction', 'PaybillController@pushtest');

	// Route::get('transactions', 'TransactionController@get_all');
	// Route::get('tests', 'TransactionController@testpage');
	// Route::get('testmpesaonline', 'TransactionController@testmpesaonline');
	// Route::post('testmpesaonline', 'TransactionController@testmpesaonline');

	// Route::resource('organization', 'OrganizationController');
	// Route::resource('paybill', 'PaybillController');
	
	
	// Route::any('creategateway', 'SetupsController@createcustomerGateway');
	// Route::any('customer/{gatewaydetails}/updategateway', 'SetupsController@updategateway');
	Route::post('checkdetails', 'OrganizationController@checkdetails');
	Route::post('updateorgsetup', 'OrganizationController@updateorgsetup');

	Route::prefix('users')->name('users.')->group(function(){
		Route::resource('/', 'UserController');
	});
});

app/User.php
<?php

namespace App;

use Hash;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Tymon\JWTAuth\Contracts\JWTSubject;
use App\Mail\UserCreated;

use Illuminate\Support\Facades\Mail;

class User extends Authenticatable implements JWTSubject, MustVerifyEmail
{
    use Notifiable;
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'organization_id', 'user_type_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * Automatically creates hash for the user password.
     *
     * @param  string  $value
     * @return void
     */
    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = Hash::make($value);
    }

    /**
     * Get the identifier that will be stored in the subject claim of the JWT.
     *
     * @return mixed
     */
    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    /**
     * Return a key value array, containing any custom claims to be added to the JWT.
     *
     * @return array
     */
    public function getJWTCustomClaims()
    {
        return [];
    }

    public function organization()
    {
        return $this->belongsTo('App\Organization');
    }

    public function usertype()
    {
        return $this->belongsTo('App\UserType', 'user_type_id');
    }

    public function getLastLoginAttribute()
    {
        if (null !== $this->lastaccess)
            return date('M d, Y H:i:s', strtotime($this->lastaccess));
        return null;
    }

    public function isAllowed()
    {
        if ($this->user_type_id == 1)
            return true;
        return false;
    }

    public function set_last_access()
    {
        $this->lastaccess = date('Y-m-d H:i:s');
        $this->save();
    }

    public function saveAndNotify()
    {
        $password = substr($this->generateRandomPassword(),8);
        $this->password = $password;
        
        if ($this->save())
            return Mail::to([$this->email])->send(new UserCreated($this, $password));
    }

    private function generateRandomPassword()
    {
        return sha1(env('SALT_PHRASE').date('Y-m-d H:i:s').rand(0,2984973872).env('HASH_PHRASE'));
    }
}

app/UserType.php
<?php

namespace App;

class UserType extends BaseModel
{
    public function companyAdmin()
    {
    	return $this->where('id', 2)->first();
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\UserType;
use App\Organization;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('users.allusers', ['users' => User::withTrashed()->get()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.create', ['roles' => UserType::get(), 'organizations' => Organization::get()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = new User($request->only(['name','email','user_type_id','organization_id']));
        $user->saveAndNotify();
        return redirect()->intended('users');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/users/allusers.blade.php
@extends('layouts.app')

@section('css_scripts')
    <link href="{{ asset('template/css/plugins/dataTables/datatables.min.css') }}" rel="stylesheet">
@endsection

@section('content')
<div class="row">
    <div class="col-lg-12">
    <div class="ibox ">
    	<div class="ibox-title">
            <h5>{{ trans_choice('app.user.user', 2) }}</h5>
        </div>
        <div class="ibox-content">
        	<a href="{{ route('users.create') }}">
        		<button class="btn btn-primary pull-right" style="margin-right: 1.5em; margin-bottom: 1em;">Create User</button>
        	</a>
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover dataTables-example" >
        	        <thead>
        		        <tr>
        		            <th>#</th>
        		            <th>Name</th>
                            <th>E-Mail</th>
                            <th>Role</th>
                            <th>Organization</th>
                            <th>Last Login</th>
        		        </tr>
        	        </thead>
        	        <tbody>
        	        @php
        	        	$count = 0;
        	        @endphp
        	        @foreach($users as $key => $user)
        	        @php
        	        	$count++;
        	        @endphp
                        <tr>
                           <td>{{ $count }}</td>
                           <td>{{ $user->name ?? '' }}</td>
                           <td>{{ $user->email ?? '' }}</td>
                           <td>{{ $user->usertype->name ?? '' }}</td>
                           <td>{{ $user->organization->organization_name ?? '' }}</td>
                           <td>{{ $user->last_login }}</td>
                        </tr>
                    @endforeach
        	        </tbody>
        	        <tfoot>
        		        <tr>
        		            <th>#</th>
        		            <th>Name</th>
                            <th>E-Mail</th>
                            <th>Role</th>
                            <th>Organization</th>
                            <th>Last Login</th>
        		        </tr>
        	        </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>
</div>
@endsection

@section('js_scripts')
    <script src="{{ asset('template/js/plugins/dataTables/datatables.min.js') }}"></script>
    <script src="{{ asset('template/js/plugins/dataTables/dataTables.bootstrap4.min.js') }}"></script>

    <script>
        $(document).ready(function(){
            $('.dataTables-example').DataTable({
                pageLength: 25,
                responsive: true,
                dom: '<"html5buttons"B>lTfgitp',
                buttons: [
                    { extend: 'copy'},
                    {extend: 'csv'},
                    {extend: 'excel', title: 'ExampleFile'},
                    {extend: 'pdf', title: 'ExampleFile'},

                    {extend: 'print',
                     customize: function (win){
                            $(win.document.body).addClass('white-bg');
                            $(win.document.body).css('font-size', '10px');

                            $(win.document.body).find('table')
                                    .addClass('compact')
                                    .css('font-size', 'inherit');
                    }
                    }
                ]

            });

        });

    </script>
@endsection

resources/views/users/create.blade.php
@extends('layouts.app')

@section('css_scripts')
    
@endsection

@section('content')
<div class="row">
<div class="col-lg-12">
        <form class="m-t" role="form" action="{{ route('users.store') }}" method="post">
            @csrf
            <div class="ibox ">
                <div class="ibox-title">
                    <h5>{{ trans_choice('app.general.add', 1) }}&nbsp;{{ trans_choice('app.user.user', 1) }}</h5>
                </div>
                <div class="ibox-content">
                    <div class="form-group  row">
                        <label class="col-sm-2 col-form-label">{{ trans_choice('app.user.name',1) }}</label>
                        <div class="col-sm-10">
                            <input type="text" name="name" id="name" class="form-control" value="{{ old('name') ?? $user->name ?? '' }}">
                        </div>
                    </div>
                    <div class="form-group  row">
                        <label class="col-sm-2 col-form-label">{{ trans_choice('app.user.email',1) }}&nbsp;{{ trans_choice('app.user.address',1) }}</label>
                        <div class="col-sm-10">
                            <input type="email" name="email" id="email" class="form-control" value="{{ old('email') ?? $user->email ?? '' }}">
                        </div>
                    </div>
                    <div class="form-group  row">
                        <label class="col-sm-2 col-form-label">{{ trans_choice('app.user.role',1) }}</label>
                        <div class="col-sm-10">
                            <select class="form-control m-b" name="user_type_id" id="role">
                                <option disabled="true" selected="true">{{ trans_choice('app.general.select',1) }}&nbsp;{{ trans_choice('app.user.role',1) }}</option>
                                @foreach($roles as $key => $role)
                                    <option value="{{ $role->id }}">{{ $role->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group  row" id="organization" style="display: none;">
                        <label class="col-sm-2 col-form-label">{{ trans_choice('app.organization.name',1) }}</label>
                        <div class="col-sm-10">
                            <select class="form-control m-b" name="organization_id">
                                <option disabled="true" selected="true">{{ trans_choice('app.general.select',1) }}&nbsp;{{ trans_choice('app.organization.organization',1) }}</option>
                                @foreach($organizations as $key => $organization)
                                    <option value="{{ $organization->id }}">{{ $organization->organization_name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>
            </div>
            <div class="ibox ">
                <div class="ibox-content">
                    <div class="form-group  row">
                        <button class="btn btn-primary" type="submit">
                            {{ __('Create') }}&nbsp;{{ trans_choice('app.user.user', 1) }}
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

@section('js_scripts')
    <script>
        $(document).ready(function(){
            $("#role").change(function(){
                role = $(this).val();
                if ((role == 2 || role == '2') || (role == 3 || role == '3')) {
                    $("#organization").show();
                } else {
                    $("#organization").hide();
                }
            });
        });
    </script>
@endsection